### ISSUE TITLE
When can the code be released?

### ISSUE THREAD

**Issue by Minato-Zackie** [JiuTian-VL/MoME#2]
Thanks for yout great work！
I am very interested in your method and code implementation. When can I expect to release the code?

**Comment by Asunatan** [comment]
+1

**Comment by daybreaksly** [comment]
Hi, thanks for your interest in our work! We are happy to let you know that we have released the code and the checkpoint. You can find them in the repository. If you have any questions or encounter any issues, feel free to reach out to us.

**Comment by Minato-Zackie** [comment]
Thank you for your prompt reply！
